### PR TITLE
Work

### PR DESCRIPTION
**Pull request by rbizzell40**
Working on create Test Case for Divide function

### CODE REVIEW

**Comment by rbizzell40** [comment]
Need to to be reviewd

**Comment by bitfield** [comment]
Don't you want to invite me to review it first? 😁

**Comment by rbizzell40** [comment]
I can't seem to put u as reviewer I invited u to my repo

**Comment by bitfield** [comment]
You can do this from the pull request page itself:

Screenshot 2020-10-17 at 17 15 46

**Comment by rbizzell40** [comment]
Ok let me try again

**Pull request closed without merging**
